name: chill_bruh
description: Making MITans lives easier.

version: 1.4.1+6

dependencies:
  flutter:
    sdk: flutter
  onesignal: ^1.0.3
  google_sign_in: ^3.2.4
  cloud_firestore: ^0.8.2+3
  firebase_auth: ^0.6.6
  firebase_analytics: ^1.0.6
  firebase_messaging: ^2.1.0
  firebase_storage: ^1.0.4
  firebase_core: ^0.2.5+1
  firebase_ml_vision: ^0.2.0+2
  font_awesome_flutter: ^8.2.0
  cupertino_icons: ^0.1.2
  cached_network_image: ^0.5.0+1
  zoomable_image: ^1.2.1+1
  photo_view: ^0.0.10
  image_picker: ^0.4.10
  carousel_slider: ^0.0.7
  url_launcher: ^4.0.1
  dynamic_theme: ^1.0.0
  flutter_local_notifications: ^0.4.1+1
  share: ^0.5.3
  shared_preferences: ^0.4.3
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.6.1


flutter_icons:
  android: true
  ios: false
  image_path: "launchericons/res/mipmap-hdpi/ic_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "launchericons/adaptive/kisspng-flat-earth-alpha.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/
    - launchericons/res/mipmap-hdpi/ic_launcher.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages